kind: Deployment
apiVersion: apps/v1
metadata:
  name: repl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repl-frontend
  template:
    metadata:
      labels:
        app: repl-frontend
    spec:
      containers:
        - name: frontend-repl
          image: omega840/repl:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: repl-secrets
                  key: DATABASE_URL
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: repl-secrets
                  key: AUTH_SECRET
            - name: AUTH_GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: repl-secrets
                  key: AUTH_GOOGLE_ID
            - name: AUTH_GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: repl-secrets
                  key: AUTH_GOOGLE_SECRET
            - name: AUTH_RESEND_KEY
              valueFrom:
                secretKeyRef:
                  name: repl-secrets
                  key: AUTH_RESEND_KEY
            - name: AUTH_TRUST_HOST
              valueFrom:
                configMapKeyRef:
                  name: repl-configmap
                  key: AUTH_TRUST_HOST
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: repl-configmap
                  key: AUTH_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: repl-configmap
                  key: NODE_ENV
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "400Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-repl-clusterip-service
spec:
  selector:
    app: repl-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
